# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Self-Hosted'
    steps:
    - task: Docker@2
      displayName: Build and Push to Docker Hub
      inputs:
        command: buildAndPush
        repository: 'hub.docker.com/repositories/el2toro/yarpapigateway'
        dockerfile: '$(Build.SourcesDirectory)/ApiGateway/YarpApiGateway/Dockerfile'
        tags: |
          $(Build.BuildId)
        buildContext: '$(Build.SourcesDirectory)'
        containerRegistry: 'dockerHubServiceConnection'  
