services:
  messagebroker: 
    image: rabbitmq:management 

  distributedcache:
    image: redis

  authdb: 
    image: mcr.microsoft.com/mssql/server

  taskdb: 
    image: mcr.microsoft.com/mssql/server
  
  tenantdb: 
    image: mcr.microsoft.com/mssql/server
  
  projectdb: 
    image: mcr.microsoft.com/mssql/server

  boarddb: 
    image: mcr.microsoft.com/mssql/server

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateway/YarpApiGateway/Dockerfile

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: Services
      dockerfile: Authentication/Auth.API/Dockerfile


  taskservice.api:
    image: ${DOCKER_REGISTRY-}taskserviceapi
    build:
      context: .
      dockerfile: Services/TaskService/TaskService.API/Dockerfile


  project.api:
    image: ${DOCKER_REGISTRY-}projectapi
    build:
      context: Services
      dockerfile: Project/Project.API/Dockerfile


  tenant.api:
    image: ${DOCKER_REGISTRY-}tenantapi
    build:
      context: Services
      dockerfile: Tenant/Tenant.API/Dockerfile

