using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Report.API.Dtos;
using static Report.API.Endpoints.ReportEndpoints;

namespace Report.API.ReportDocuments;

public class ReportDocument(AnaliticsDto report, ReportRequest request) : IDocument
{
    public DocumentMetadata GetMetadata() => new DocumentMetadata
    {
        Title = request.name,
        Subject = request.description,
        CreationDate = DateTime.Now
    };

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(40);
            page.Header().PaddingBottom(50)
                .Text("Projects Analytics Report")
                .SemiBold().FontSize(24).FontColor(Colors.Blue.Medium).AlignCenter();

            page.Content()
                .Column(col =>
                {
                    col.Item().PaddingBottom(40).Text(request.description).FontSize(14);

                    col.Item().PaddingBottom(20).Text(text =>
                    {
                        text.Span("Report ID: ");
                        text.Span(Guid.NewGuid().ToString()).Bold();
                    });
                    col.Item().PaddingBottom(20).Text(text =>
                    {
                        text.Span($"Completed Projects: ");
                        text.Span($"{report.ProjectCompletitionRate}%").Bold();
                    });
                    col.Item().PaddingBottom(20).Text(text =>
                    {
                        text.Span("Overdue Tasks: ");
                        text.Span($"{report.OverdueTasks}").Bold();
                    });
                    col.Item().PaddingBottom(20).Text(text =>
                    {
                        text.Span("Budget Usage: ");
                        text.Span($"{report.BudgetUsage:C}").Bold();
                    });
                    col.Item().PaddingBottom(20).Text(text =>
                    {
                        text.Span($"Completion Rate: ");
                        text.Span($"{report.ProjectCompletitionRate:F2}%").Bold();
                    });
                    col.Item().PaddingBottom(20).Text(text =>
                    {
                        text.Span($"Generated At: ");
                        text.Span($"{DateTime.UtcNow}").Bold();
                    });
                });

            page.Footer()
                .AlignCenter()
                .Text(txt =>
                {
                    txt.Span("Generated by Project Management System");
                });
        });
    }
}

