apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-api
  labels:
    app: board-api
spec:
  replicas: 2  # number of pods
  selector:
    matchLabels:
      app: board-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: board-api
    spec:
      containers:
        - name: board-api
          # Use placeholder for image tag; DevOps pipeline can override it
          image: el2toro/boardapi:latest
          ports:
            - containerPort: 8080
          # Optional: define environment variables if your app needs them
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
      # If using private Docker Hub images, include the secret:
      # imagePullSecrets:
      #   - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: board-api-service
spec:
  type: ClusterIP  # public access; use ClusterIP if internal only
  selector:
    app: board-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
