global using Mapster;
global using MediatR;
global using TaskService.Application.Dtos;
global using TaskService.Domain.Entities;
global using TaskService.Domain.Interfaces;
global using Core.Messaging.Events.Task;
global using MassTransit;
global using Microsoft.Extensions.Logging;
global using TaskService.Application.Interfaces;
